{"id": null, "input_data": {"id": "3", "schema_name": "qcschema_input", "schema_version": 1, "molecule": {"schema_name": "qcschema_molecule", "schema_version": 2, "validated": true, "symbols": ["O", "H", "H", "O", "H", "H"], "geometry": [1.29257274, -3.2446599, -3.94007921, 0.75022131, -2.11460352, -2.73254395, 2.22609735, -4.12527227, -5.29879189, -1.15273297, 2.01633787, 0.86927408, -0.59715348, 0.3325918, 0.66707331, -1.73854816, 3.71331191, 1.19052744], "name": "H4O2", "molecular_charge": 0.0, "molecular_multiplicity": 1, "fix_com": false, "fix_orientation": false, "provenance": {"creator": "QCElemental", "version": "v0.23.0", "routine": "qcelemental.molparse.from_schema"}}, "driver": "gradient", "model": {"method": "fail", "basis": "6-31gss"}, "keywords": {}, "protocols": {}, "extras": {}, "provenance": {"creator": "QCElemental", "version": "v0.23.0", "routine": "qcelemental.models.results", "cpu": "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz", "hostname": "1ee1a2d8cf4c", "username": "root", "qcengine_version": "v0.18.0+36.g0490362", "wall_time": 0.004443645477294922}}, "success": false, "error": {"error_type": "unknown_error", "error_message": "QCEngine Execution Error:\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.7/site-packages/qcengine/util.py\", line 114, in compute_wrapper\n    yield metadata\n  File \"/opt/conda/lib/python3.7/site-packages/qcengine/compute.py\", line 91, in compute\n    output_data = executor.compute(input_data, config)\n  File \"/opt/conda/lib/python3.7/site-packages/qcengine/programs/terachem_pbs.py\", line 103, in compute\n    return client.compute(input_model)\n  File \"/opt/conda/lib/python3.7/site-packages/tcpb/tcpb.py\", line 152, in compute\n    job_input_msg = atomic_input_to_job_input(atomic_input)\n  File \"/opt/conda/lib/python3.7/site-packages/tcpb/utils.py\", line 48, in atomic_input_to_job_input\n    ji.method = pb.JobInput.MethodType.Value(ai_copy.model.method.upper())\n  File \"/opt/conda/lib/python3.7/site-packages/google/protobuf/internal/enum_type_wrapper.py\", line 76, in Value\n    self._enum_type.name, name))\nValueError: Enum MethodType has no value defined for name 'FAIL'\n", "extras": null}, "extras": null}